// Code generated by goctl. DO NOT EDIT.
package types

type HelloReq struct {
	Name string `path:"name"`
}

type HelloResp struct {
	Message string `json:"message"`
}

type HelloWorld struct {
	Message string `json:"message"`
}

type Request struct {
	Name string `path:"name"`
}

type Response struct {
	Message string `json:"message"`
}
