// Code generated by goctl. DO NOT EDIT.
// Source: helllo.proto

package server

import (
	"context"

	"helllo/helllo"
	"helllo/internal/logic"
	"helllo/internal/svc"
)

type HellloServer struct {
	svcCtx *svc.ServiceContext
	helllo.UnimplementedHellloServer
}

func NewHellloServer(svcCtx *svc.ServiceContext) *HellloServer {
	return &HellloServer{
		svcCtx: svcCtx,
	}
}

func (s *HellloServer) Ping(ctx context.Context, in *helllo.Request) (*helllo.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
