// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: helllo.proto

package helllo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Helllo_Ping_FullMethodName = "/helllo.Helllo/Ping"
)

// HellloClient is the client API for Helllo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HellloClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type hellloClient struct {
	cc grpc.ClientConnInterface
}

func NewHellloClient(cc grpc.ClientConnInterface) HellloClient {
	return &hellloClient{cc}
}

func (c *hellloClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Helllo_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HellloServer is the server API for Helllo service.
// All implementations must embed UnimplementedHellloServer
// for forward compatibility
type HellloServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedHellloServer()
}

// UnimplementedHellloServer must be embedded to have forward compatible implementations.
type UnimplementedHellloServer struct {
}

func (UnimplementedHellloServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedHellloServer) mustEmbedUnimplementedHellloServer() {}

// UnsafeHellloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HellloServer will
// result in compilation errors.
type UnsafeHellloServer interface {
	mustEmbedUnimplementedHellloServer()
}

func RegisterHellloServer(s grpc.ServiceRegistrar, srv HellloServer) {
	s.RegisterService(&Helllo_ServiceDesc, srv)
}

func _Helllo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HellloServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helllo_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HellloServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Helllo_ServiceDesc is the grpc.ServiceDesc for Helllo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Helllo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helllo.Helllo",
	HandlerType: (*HellloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Helllo_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helllo.proto",
}
