// Code generated by goctl. DO NOT EDIT.
// Source: helllo.proto

package hellloclient

import (
	"context"

	"helllo/helllo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = helllo.Request
	Response = helllo.Response

	Helllo interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultHelllo struct {
		cli zrpc.Client
	}
)

func NewHelllo(cli zrpc.Client) Helllo {
	return &defaultHelllo{
		cli: cli,
	}
}

func (m *defaultHelllo) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := helllo.NewHellloClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
